name: cassandra-multi-dc
services:
  # seed node 1 (DC1)
  cassandra11:
    image: cassandra:latest
    container_name: cassandra11
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.11
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.11
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    networks:
      dc1_net:
        ipv4_address: 172.16.1.11
      common_net:
        ipv4_address: 172.16.0.11
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # seed node 2 (DC2)
  cassandra21:
    image: cassandra:latest
    container_name: cassandra21
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.21
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.21
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    depends_on:
      cassandra11:
        condition: service_healthy
    networks:
      dc2_net:
        ipv4_address: 172.16.2.21
      common_net:
        ipv4_address: 172.16.0.21
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # COMMON NODES
  cassandra12:
    image: cassandra:latest
    container_name: cassandra12
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.12
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.12
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    depends_on:
      cassandra21:
        condition: service_healthy
    networks:
      dc1_net:
        ipv4_address: 172.16.1.12
      common_net:
        ipv4_address: 172.16.0.12
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra13:
    image: cassandra:latest
    container_name: cassandra13
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.13
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.13
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    depends_on:
      cassandra12:
        condition: service_healthy
    networks:
      dc1_net:
        ipv4_address: 172.16.1.13
      common_net:
        ipv4_address: 172.16.0.13
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra22:
    image: cassandra:latest
    container_name: cassandra22
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.22
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.22
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    depends_on:
      cassandra13:
        condition: service_healthy
    networks:
      dc2_net:
        ipv4_address: 172.16.2.22
      common_net:
        ipv4_address: 172.16.0.22
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra23:
    image: cassandra:latest
    container_name: cassandra23
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.0.23
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.23
      - CASSANDRA_SEEDS=172.16.0.11,172.16.0.21
      - CASSANDRA_PREFER_LOCAL=true
    depends_on:
      cassandra22:
        condition: service_healthy
    networks:
      dc2_net:
        ipv4_address: 172.16.2.23
      common_net:
        ipv4_address: 172.16.0.23
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  common_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  dc1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  dc2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24
