name: cassandra-cluster
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.1.2
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.2
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    networks:
      common_net:
        ipv4_address: 172.16.0.2
      dc1_net:
        ipv4_address: 172.16.1.2
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.1.3
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.3
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    depends_on:
      cassandra1:
        condition: service_healthy
    networks:
      common_net:
        ipv4_address: 172.16.0.3
      dc1_net:
        ipv4_address: 172.16.1.3
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.1.4
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.4
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    depends_on:
      cassandra2:
        condition: service_healthy
    networks:
      common_net:
        ipv4_address: 172.16.0.4
      dc1_net:
        ipv4_address: 172.16.1.4
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra4:
    image: cassandra:latest
    container_name: cassandra4
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.2.2
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.5
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    depends_on:
      cassandra3:
        condition: service_healthy
    networks:
      common_net:
        ipv4_address: 172.16.0.5
      dc2_net:
        ipv4_address: 172.16.2.2
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra5:
    image: cassandra:latest
    container_name: cassandra5
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.2.3
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.6
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    depends_on:
      cassandra4:
        condition: service_healthy
    networks:
      common_net:
        ipv4_address: 172.16.0.6
      dc2_net:
        ipv4_address: 172.16.2.3
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra6:
    image: cassandra:latest
    container_name: cassandra6
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=172.16.2.4
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.7
      - CASSANDRA_SEEDS=172.16.0.2,172.16.0.5
    depends_on:
      cassandra5:
        condition: service_healthy
    networks:
      common_net:
        ipv4_address: 172.16.0.7
      dc2_net:
        ipv4_address: 172.16.2.4
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  common_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  dc1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  dc2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24
