name: infobarbankdb
services:
  cassandra1:
    container_name: cassandra1
    image: cassandra:latest
    environment:
      - "CASSANDRA_SEEDS=cassandra1"
      - "CASSANDRA_CLUSTER_NAME=infobarbankdb"
      - "CASSANDRA_DC=BRA-SP-OLTP"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    expose:
      - 9042
    ports:
      - "19042:9042"
  cassandra2:
    container_name: cassandra2
    image: cassandra:latest
    environment:
      - "CASSANDRA_SEEDS=cassandra1"
      - "CASSANDRA_CLUSTER_NAME=infobarbankdb"
      - "CASSANDRA_DC=BRA-SP-OLTP"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra1
    expose:
      - 9042
    ports:
      - "29042:9042"
  cassandra3:
    container_name: cassandra3
    image: cassandra:latest
    environment:
      - "CASSANDRA_SEEDS=cassandra1"
      - "CASSANDRA_CLUSTER_NAME=infobarbankdb"
      - "CASSANDRA_DC=BRA-SP-OLTP"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra1
    expose:
      - 9042
    ports:
      - "39042:9042"
