name: cassandra-standalone
services:
  cassandra-database:
    image: cassandra:latest
    container_name: cassandra-database
    environment:
      - CASSANDRA_CLUSTER_NAME=infobarbosainc
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=172.16.0.11
      - CASSANDRA_SEEDS=172.16.0.11
    networks:
      common_net:
        ipv4_address: 172.16.0.11
    restart:
      on-failure
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5

  cassandra-init-infobarbank:
    image: infobarbosa/infobarbank-cassandra-schema:latest
    container_name: cassandra-init-infobarbank
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-database
      - CASSANDRA_REPLICATION_FACTOR=1
    depends_on:
      cassandra-database:
        condition: service_healthy
    networks:
      - common_net
    restart:
      on-failure

  cassandra-init-ecommerce:
    image: infobarbosa/cassandra-schema-ecommerce:latest
    container_name: cassandra-init-ecommerce
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-database
      - CASSANDRA_REPLICATION_FACTOR=1
    depends_on:
      cassandra-database:
        condition: service_healthy
    networks:
      - common_net
    restart:
      on-failure

networks:
  common_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
